<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Manual Decision</name>
  <uuid>5a826f39-ce1b-494e-9d45-6d3e21606bb0</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    'the validate time window' is manual
    or 'the validate type of goods' is manual
then
    set decision to manual ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
