<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>934e3857-8b12-4b14-9a2f-6dcdb0dcc6a0</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to approved ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
